# Workflow to nightly build and test the library
name: Nightly tests

on:
  schedule:
    # Everyday at 3:42 UTC
    - cron: "42 3 */1 * *"

jobs:
  test:
    name: Build and test the library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/install.sh

      - name: Test library
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_script.sh

      - name: Test documentation
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_docs.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
